# Generated by Django 4.1.2 on 2022-10-07 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('dept_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=200)),
                ('emp_surname', models.CharField(max_length=200)),
                ('emp_email', models.EmailField(max_length=200)),
                ('emp_photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('emp_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.departments')),
            ],
        ),
    ]
